//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::fruits::{
        ActiveModel as FruitsActiveModel, Column as FruitsColumn, Entity as Fruits,
        Model as FruitsModel, PrimaryKey as FruitsPrimaryKey, Relation as FruitsRelation,
    };
