//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::suppliers::{
    ActiveModel as SuppliersActiveModel, Column as SuppliersColumn, Entity as Suppliers,
    Model as SuppliersModel, PrimaryKey as SuppliersPrimaryKey, Relation as SuppliersRelation,
};
